Auth
charconstpointer/gadget pull request #53
Opened 2021-03-11 11:49 UTC by mojski

2021-03-11 12:03 UTC, charconstpointer requested changes

2021-03-11 12:03 UTC, charconstpointer commented on Gadget.Server/Authorization/Services/Interfaces/IAuthorizationService.cs
> +    public interface IAuthorizationService
potrzebne?

2021-03-11 12:03 UTC, charconstpointer commented on Gadget.Server/Authorization/Services/Interfaces/IUserService.cs
>      public interface IUserService
uzywaj liczby mnogiej w tych nazewnictwach, chyba ze w ogole IAuthService jest lepsza nzwa

2021-03-11 12:03 UTC, charconstpointer commented on Gadget.Server/Authorization/Services/Interfaces/IUserService.cs
>          Task<bool> IsUservalid(string userName, string password);
pascal case IsUserValid

2021-03-11 12:03 UTC, charconstpointer commented on Gadget.Server/Authorization/Services/AuthorizationService.cs
> +    public class AuthorizationService : IAuthorizationService
potrzebne?

2021-03-11 12:03 UTC, charconstpointer commented on Gadget.Server/Authorization/Services/UserService.cs
> +           var newJWT = _tokenManager.GenerateToken(user.UserName);
newToken?

2021-03-11 12:03 UTC, charconstpointer commented on Gadget.Server/Authorization/AuthorizationController.cs
> @@ -28,6 +28,7 @@
jak juz ta metoda nie jest potrzebna to usun

2021-03-11 12:03 UTC, charconstpointer commented on Gadget.Server/Authorization/AuthorizationController.cs
> @@ -38,7 +39,7 @@
usun to wszystko z controllera

2021-03-11 12:03 UTC, charconstpointer commented on Gadget.Server/Authorization/AuthorizationController.cs
> @@ -46,22 +47,31 @@
czy ta metoda jest w ogole potrzebna?

2021-03-11 12:03 UTC, charconstpointer commented on Gadget.Server/Authorization/AuthorizationController.cs
> -        [HttpPost]
nazwa tej metody jest dziwna, gdy to czytam if ValidateToken == true to unauthorized? co ta metoda robi, bo z nazwy ciezko wyczuc

2021-03-11 12:03 UTC, charconstpointer commented on Gadget.Server/Authorization/AuthorizationController.cs
> +            SetTokenCookie(newToken.RefreshToken);
to tez niech zmyka z controllera

2021-03-11 12:03 UTC, charconstpointer commented on Gadget.Server/Domain/Entities/RefreshToken.cs
> +        public void Use()
do tego mozna settera uzyc, chyba ze jest jakis powod dla ktorego wolisz zostac przy tym

2021-03-16 10:27 UTC, mojski commented on Gadget.Server/Authorization/Services/Interfaces/IAuthorizationService.cs
> +    public interface IAuthorizationService
Faktycznie zpomniałem, miało się tam coś znaleźć ale ostatecznie wylądowało w UserService. Usunąłem

2021-03-16 10:31 UTC, mojski commented on Gadget.Server/Authorization/Services/Interfaces/IUserService.cs
>          Task<bool> IsUservalid(string userName, string password);
dzięki, poprawiam

2021-03-16 10:32 UTC, mojski commented on Gadget.Server/Authorization/Services/AuthorizationService.cs
> +    public class AuthorizationService : IAuthorizationService
jak wyżej, usuwam

2021-03-16 10:34 UTC, mojski commented on Gadget.Server/Authorization/Services/UserService.cs
> +           var newJWT = _tokenManager.GenerateToken(user.UserName);
poprawione

2021-03-16 10:35 UTC, mojski commented on Gadget.Server/Authorization/AuthorizationController.cs
> @@ -28,6 +28,7 @@
Jeszcze będzie potrzebna, bo będę jeszcze jej używał

2021-03-16 11:01 UTC, mojski commented on Gadget.Server/Authorization/AuthorizationController.cs
> +            SetTokenCookie(newToken.RefreshToken);
zrobione

2021-03-16 11:04 UTC, mojski commented on Gadget.Server/Domain/Entities/RefreshToken.cs
> +        public void Use()
Powodu nie ma, zmieniłem.

2021-03-16 11:22 UTC, mojski commented on Gadget.Server/Authorization/AuthorizationController.cs
> @@ -38,7 +39,7 @@
zrobione

2021-03-16 11:28 UTC, mojski commented on Gadget.Server/Authorization/AuthorizationController.cs
> @@ -46,22 +47,31 @@
jeszcze jej poużywam

2021-03-16 11:28 UTC, merged